In [1]:
import torch
import numpy 

In [2]:
x = torch.zeros(4,3)

In [3]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
y = torch.rand(4,3)

In [5]:
y

tensor([[0.7206, 0.7671, 0.1026],
        [0.8758, 0.5615, 0.4104],
        [0.4095, 0.5284, 0.2358],
        [0.7057, 0.8597, 0.5278]])

In [6]:
x.size()

torch.Size([4, 3])

In [7]:
print(x+y)

tensor([[0.7206, 0.7671, 0.1026],
        [0.8758, 0.5615, 0.4104],
        [0.4095, 0.5284, 0.2358],
        [0.7057, 0.8597, 0.5278]])


# Automatic Differentiation PyTorch

In [8]:
import torch

In [9]:
a = torch.tensor([2.],requires_grad=True)
b = torch.tensor([6.],requires_grad=True)

In [10]:
L = 2*a**2-4*b**2

In [11]:
L.backward()

In [12]:
print(a.grad.data,b.grad.data)

tensor([8.]) tensor([-48.])


# Why Use Deep Neural Networks (DNNs) in Machine Learning

## Universal Approximation Theorem
DNNs have the ability to approximate any continuous function given sufficient data and computational resources.

## Advantages of DNNs
DNNs can leverage large amounts of training data, which allows them to perform better than many classical machine learning algorithms.

# Supervised Learning (Classifier, Regressor)

## How It Works
In supervised learning, a neural network accepts an input as a vector and predicts an output. This can be used for tasks such as classification and regression.

![DNN](DNN.png)

The weighted sum formula for a perceptron involves multiplying each input feature \( x_i \) by its corresponding weight \( w_i \) and then summing these products. For \( n \) input features, the formula can be written as:

z = is weighted sum

z = w1x1 + w1x2 + ... + wnxn = XTW

this z is further processed by an activation function to produce the output.

![Perceptron](Perceptron.png)

# PERCEPTRON WITH PYTORCH

In [13]:
import numpy as np
import torch
import torch.nn as nn
import sys

In [14]:
def wSum(X,W):
    h = torch.tensor(X, dtype=torch.float32)
    z = torch.matmul(W,h)
    return z


In [15]:
inputDim = 10
n = 1000
X = np.random.rand(n,inputDim)
y = np.random.randint(0,2,n)

In [16]:
W = torch.tensor(np.random.uniform(0,1,inputDim),requires_grad=True)

In [17]:
z = wSum(X[0,:],W)

RuntimeError: dot : expected both vectors to have same dtype, but found Double and Float

In [ ]:
print(z)

# Weights 
![](Weights.png)

### Every neuron incoming input plus 1 for baise is the total no of weights on that individual neuron.

In [ ]:
def forwardStep(X,W_list):
    h = torch.from_numpy(X)
    for W in W_list:
        z = torch.matmul(W,h)
        h = activate(z)
    return h

In [ ]:
inputDim = 10
n = 1000
X = np.random.rand(n,inputDim)
y = np.random.randint(0,2,n)

W1 = torch.tensor(np.random.uniform(0,1,(2,inputDim)),requires_grad=True)
W2 = torch.tensor(np.random.uniform(0,1,(3,2)),requires_grad=True)
W3 = torch.tensor(np.random.uniform(0,1,(1,3)),requires_grad=True)

W_list = []
W_list.append(W1)
W_list.append(W2)
W_list.append(W3)
z = forwardStep(X[0,:],W_list)
print(z)

RuntimeError: Numpy is not available

In [ ]:
print(y_hat,y)

# Gradient Decent and Loss Function

In [ ]:
def activate(x):
    return 1 / (1 + torch.exp(-x))

In [ ]:
def updateParams(W_list, dW_list, lr):
    with torch.no_grad():
        for i in range(len(W_list)):
            W_list[i] -= lr * dW_list[i]
    return W_list

In [ ]:
def trainNN_sgd(X, y, W_list, loss_fn, lr=0.0001, nepochs=100):
    for epoch in range(nepochs):
        avgLoss = []
        for i in range(len(y)):
            Xin = X[i, :]
            yTrue = y[i]
            y_hat = forwardStep(Xin, W_list)
            loss = loss_fn(y_hat, torch.tensor(yTrue, dtype=torch.double))
            loss.backward()
            avgLoss.append(loss.item())
            sys.stdout.flush()
            dW_list = []
            for j in range(len(W_list)):
                dW_list.append(W_list[j].grad.data)
            W_list = updateParams(W_list, dW_list, lr)
            for j in range(len(W_list)):
                W_list[j].grad.data.zero_()
        print("Loss after epoch=%d: %f" % (epoch, np.mean(np.array(avgLoss))))
    return W_list

[![](https://mermaid.ink/img/pako:eNplkctygjAUhl8lc9bogIhSFu1U8dppN7aLFlycgRQySsKEMF5590LE6rRZJef7_uQkOUEkYgoeJBLzlLz7ISf1eA5WCqVak07nkYyCBWeK4ZYdKdlRlqSqWF-8kRbGwVRIQjFKCc1FlLZwrKF_g0oi44wnhO4xy7e09XztTRpvhzImuRQ5JqiY4K0x0cY0GIssLxUlW1FcO5hqNAtGGG3-B2eazoOPPEb1t_m5hovTq5D02lLxVF3gooHnT1qciX9feRNnsmwjzV1_A8tbYHxfaQIvwYTH9algQEZlhiyuX_zUWCGolGY0BK-exig3IYS8qj0slVgdeASekiU1oNQ38BnWH5WB943boq7myL-EyK5SvQTvBHvwnJ7dNQcPpuValjN0B44BB_Bss-v2e647tPrWwHT6tlsZcNQbmN0Ha9CzXccaOqbdd-2eAVKUSdqeVf0AGhOoNg?type=png)](https://mermaid.live/edit#pako:eNplkctygjAUhl8lc9bogIhSFu1U8dppN7aLFlycgRQySsKEMF5590LE6rRZJef7_uQkOUEkYgoeJBLzlLz7ISf1eA5WCqVak07nkYyCBWeK4ZYdKdlRlqSqWF-8kRbGwVRIQjFKCc1FlLZwrKF_g0oi44wnhO4xy7e09XztTRpvhzImuRQ5JqiY4K0x0cY0GIssLxUlW1FcO5hqNAtGGG3-B2eazoOPPEb1t_m5hovTq5D02lLxVF3gooHnT1qciX9feRNnsmwjzV1_A8tbYHxfaQIvwYTH9algQEZlhiyuX_zUWCGolGY0BK-exig3IYS8qj0slVgdeASekiU1oNQ38BnWH5WB943boq7myL-EyK5SvQTvBHvwnJ7dNQcPpuValjN0B44BB_Bss-v2e647tPrWwHT6tlsZcNQbmN0Ha9CzXccaOqbdd-2eAVKUSdqeVf0AGhOoNg)

In [ ]:
def trainNN_batch(X,y,W_list,loss_fn,lr=0.0001,nepochs=100):
    n = len(y)
    for epoch in range(nepochs):
        loss = 0
        for i in range(n):
            Xin = X[i,:]
            yTrue = y[i]
            y_hat = forwardStep(Xin,W_list)
            loss += loss_fn(y_hat,torch.tensor(yTrue,dtype=torch.double))
        loss = loss/n
        loss.backward()
        sys.stdout.flush()
        dW_list = []
        for j in range(len(W_list)):
            dW_list.append(W_list[j].grad.data)
        W_list = updateParams(W_list,dW_list,lr)
        for j in range(len(W_list)):
            W_list[j].grad.data.zero_()
        print("Loss after epoch=%d: %f" %(epoch,loss))
    return W_list


In [ ]:
def trainNN_minibatch(X,y,W_list,loss_fn,lr=0.0001,nepochs=100,batchSize=16):
    n = len(y)
    numBatches = n//batchSize
    
    for epoch in range(nepochs):
        for batch in range(numBatches):
            X_batch = X[batch*batchSize:(batch+1)*batchSize,:]
            y_batch = y[batch*batchSize:(batch+1)*batchSize]
            loss = 0
            for i in range(batchSize):
                Xin = X_batch[i,:]
                yTrue = y_batch[i]
                y_hat = forwardStep(Xin,W_list)
                loss += loss_fn(y_hat,torch.tensor(yTrue,dtype=torch.double))
            loss = loss/batchSize
            loss.backward()
            sys.stdout.flush()
            dW_list = []
            for j in range(len(W_list)):
                dW_list.append(W_list[j].grad.data)
            W_list = updateParams(W_list,dW_list,lr)
            for j in range(len(W_list)):
                W_list[j].grad.data.zero_()
        print("Loss after epoch=%d: %f" %(epoch,loss/numBatches))
    return W_list

In [ ]:
inputDim = 10
n = 1000
X = np.random.rand(n,inputDim)
y = np.random.randint(0,2,n)

W1 = torch.tensor(np.random.uniform(0,1,(2,inputDim)),requires_grad=True)
W2 = torch.tensor(np.random.uniform(0,1,(3,2)),requires_grad=True)
W3 = torch.tensor(np.random.uniform(0,1,3),requires_grad=True)

W_list = []
W_list.append(W1)
W_list.append(W2)
W_list.append(W3)

loss_fn = nn.BCELoss()
W_list = trainNN_sgd(X,y,W_list,loss_fn,lr=0.0001,nepochs=100)


In [ ]:
m = nn.Sigmoid()
loss_fun = nn.BCELoss
lr = 0.0001
x = torch.randn(1)
y = torch.randint(0,2,(0,1), dtype = torch.float)
w = torch.randn(1, requires_grad=True)


In [ ]:
nIter = 100
for i in range(nIter):
    y_hat = m(w*x)
    loss = loss_fun(y_hat,y)
    loss.backward()
    dw = w.grad.data
    with torch.no_grad():
        w -= lr*dw
    w.grad.data.zero_()
    print(loss.item())

# A Neural network has non-linear activation functions. then its called as neural network

# MDP 

![](MDP.png)

framework for modeling decision making in situations where outcomes are partly random and partly under the control of a decision maker

# ACTIVATION FUNCTIONS

In [ ]:
activation_fun = nn.Sigmoid()
x = 100*torch.randn(1)
print(x,activation_fun(x))

# todo the bigger the number sigmoid will output the closer to 1 and vice versa

In [ ]:
activation_fun = nn.ReLU()
x = 100*torch.randn(1)
print(x,activation_fun(x))

# todo if the number is negative it will output 0 and if it is positive it will output the number

## Loss Function

In [ ]:
activation_fun = nn.Sigmoid()
x = torch.randn(1)
y = torch.randint(0,2,(1,),dtype=torch.float)
y_hat = activation_fun(x)
loss_fun = nn.BCELoss()
loss_value = loss_fun(y_hat,y)
print(loss_value.item())

# todo if the number is negative it will output 0 and if it is positive it will output the number

# PYTORCH IMPLEMENTATION OF NEURAL NETWORK FULLY CONNECTED 

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader

In [ ]:
inputDim = 10
n = 1000
X = np.random.rand(n,inputDim)
y = np.random.randint(0,2,n)

tensor_x = torch.Tensor(X)
tensor_y = torch.Tensor(y)
Xy = TensorDataset(tensor_x,tensor_y)
Xy_loader = DataLoader(Xy,batch_size=16,shuffle=True,drop_last=True)


In [ ]:
model = nn.Sequential(
    nn.Linear(inputDim,200),
    nn.ReLU(),
    nn.BatchNorm1d(num_features=200),
    nn.Dropout(0.5),
    nn.Linear(200,100),
    nn.Tanh(),
    nn.BatchNorm1d(num_features=100),
    nn.Linear(100,1),
    nn.Sigmoid()
)


In [ ]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)


In [ ]:
loss_fn = nn.BCELoss()

In [ ]:
import torch
import numpy as np

# Ensure NumPy is available
try:
    import numpy as np
except ImportError:
    raise RuntimeError("Numpy is not available")

nepochs = 100
for epoch in range(nepochs):
    for X, y in Xy_loader:
        batch_size = X.shape[0]
        y_hat = model(X.view(batch_size, -1))
        
        # Reshape y to match y_hat's shape
        y = y.view_as(y_hat)
        
        loss = loss_fn(y_hat, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(float(loss))


0.6855936050415039
0.7457056045532227
0.632402241230011
0.73485267162323
0.7375826239585876
0.7483521699905396
0.6166559457778931
0.6985070705413818
0.6339077353477478
0.7038643956184387
0.6778419017791748
0.7039530277252197
0.6300564408302307
0.6448913216590881
0.7625095844268799
0.7205974459648132
0.6668219566345215
0.720833420753479
0.7404969930648804
0.6569193601608276
0.5139963626861572
0.6820937395095825
0.5406128168106079
0.6147273182868958
0.6223942637443542
0.5815938711166382
0.6043765544891357
0.6376553773880005
0.7194736003875732
0.590983510017395
0.7603735327720642
0.47641080617904663
0.7361555099487305
0.5252870321273804
0.5708986520767212
0.5991623997688293
0.6995691061019897
0.6001617908477783
0.5062424540519714
0.7035475969314575
0.5171946287155151
0.6610448956489563
0.5423425436019897
0.7610658407211304
0.6877316236495972
0.5319892764091492
0.5198844075202942
0.5883615612983704
0.6779106259346008
0.521933376789093
0.921233057975769
0.48555877804756165
0.582386612892150

In [ ]:
import numpy as np
with torch.no_grad():
    xt = torch.tensor(np.random.rand(1,inputDim))
    y2 = model(xt.float())
    print(y2.detach().numpy()[0][0])