In [94]:
import numpy as np
import gymnasium as gym
import random

In [95]:
env = gym.make("FrozenLake-v1", is_slippery=False,render_mode="ansi")

In [96]:
action_space_size =  env.action_space.n
state_space_size = env.observation_space.n 

In [97]:
q_table = np.zeros((state_space_size, action_space_size))

In [98]:
total_episodes = 30000
learning_rate = 0.2
max_steps = 100
gamma = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [99]:
rewards = []

for episode in range(total_episodes):
    state, _ = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        if random.uniform(0, 1) > epsilon:
            action = np.argmax(qtable[state, :])  # Exploit
        else:
            action = env.action_space.sample()  # Explore

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        max_new_state = np.max(qtable[new_state, :])

        qtable[state, action] = qtable[state, action] + learning_rate * (
            reward + gamma * max_new_state - qtable[state, action]
        )
        total_rewards += reward

        state = new_state
        if done:
            break

    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)

print("Score:", str(sum(rewards) / total_episodes))
print(qtable)

Score: 0.9531666666666667
[[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.95095525 0.9509469 ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [100]:
env.reset()

for episode in range(10):
    state, _ = env.reset()
    step = 0
    done = False

    print("Episode:", episode + 1)

    for step in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        env.render()
        if done:

            print("Number of Steps:", step)
            break
        state = new_state

env.close()

Episode: 1
Number of Steps: 5
Episode: 2
Number of Steps: 5
Episode: 3
Number of Steps: 5
Episode: 4
Number of Steps: 5
Episode: 5
Number of Steps: 5
Episode: 6
Number of Steps: 5
Episode: 7
Number of Steps: 5
Episode: 8
Number of Steps: 5
Episode: 9
Number of Steps: 5
Episode: 10
Number of Steps: 5
